CREATE TABLE Region (
    RegionID INT IDENTITY PRIMARY KEY,
    RegionName NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TimeOfUseCodes (
    TOUCodeID INT IDENTITY PRIMARY KEY,
    Code NVARCHAR(50) UNIQUE NOT NULL,
    Description NVARCHAR(200)
);

CREATE TABLE RateClasses (
    RateClassID INT IDENTITY PRIMARY KEY,
    ClassName NVARCHAR(100) UNIQUE NOT NULL,
    Description NVARCHAR(200)
);
