version: '3.8'
services:
  airflow-webserver:
    volumes:
      # Mount specific directories instead of entire workspace
      - ../../airflow/dags:/opt/airflow/dags:cached
      - ../../airflow/plugins:/opt/airflow/plugins:cached
      - ../../airflow/logs:/opt/airflow/logs:cached
      - ../../airflow/config/airflow.cfg:/opt/airflow/airflow.cfg:cached
      
    working_dir: /opt/airflow
    
    # Keep container running but don't interfere with Airflow
    command: sleep infinity
    
    # Preserve the Airflow user and environment
    user: airflow
    environment:
      - PYTHONPATH=/opt/airflow/dags:/opt/airflow/plugins:/usr/local/lib/python3.10/site-packages
